import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        {/* contexto -> sesion del usuario, funciones para hacer login, para hacer logout... */}
        <SessionAuthProvider>
          {children}
        </SessionAuthProvider>
        {/* contexto */}
      </body>
    </html>
  );
}
