### Registrar un nuevo usuario
POST https://mockmentor.4.us-1.fl0.io/auth/register
Content-Type: application/json

{
  "firstname": "Alonso",
  "lastname": "Villazón",
  "email": "avillazon@budgetapp.com",
  "password": "Welcome@987"
}

### Login
POST https://mockmentor.4.us-1.fl0.io/auth/login
Content-Type: application/json

{
  "email": "avillazon@budgetapp.com",
  "password": "Welcome@987"
}

### Recuperar los invoices de un usuario que hizo login
GET https://mockmentor.4.us-1.fl0.io/api/v1/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTYxMTIxMywiZXhwIjoxNzA5NjE0ODEzfQ.puKArpOy1WnmbbjqB3NWDIM6ADGd0KAE_gmNeWtAndg

### Creamos una nueva invoice
POST https://mockmentor.4.us-1.fl0.io/api/v1/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTYxMTIxMywiZXhwIjoxNzA5NjE0ODEzfQ.puKArpOy1WnmbbjqB3NWDIM6ADGd0KAE_gmNeWtAndg

{
  "bill_from_street_address": "Ap #248-9587 Tortor, Av.",
  "bill_from_city": "Chiclayo",
  "bill_from_postCode": "687775",
  "bill_from_country": "Peru",
  "bill_to_client_name": "Kimberly Tucker",
  "bill_to_client_email": "dictum.proin@yahoo.com",
  "bill_to_street_address": "P.O. Box 666, 3606 Sem Road",
  "bill_to_city": "Kidapawan",
  "bill_to_post_code": "T54 8AX",
  "bill_to_country": "South Korea",
  "date": "2024-04-16T06:43:19Z",
  "payment_terms": "Next 30 Days",
  "project_description": "Graphic Design",
  "items": []
}


### Recuperar los budgets de un usuario que hizo login
GET https://mockmentor.4.us-1.fl0.io/api/v1/budgets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

### Creamos un budget
POST https://mockmentor.4.us-1.fl0.io/api/v1/budgets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

{
  "amount": 0
}

### Actualizamos un budget
PUT https://mockmentor.4.us-1.fl0.io/api/v1/budgets/7642b5bb-d52c-449f-aae7-b99e4c162464
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

{
  "amount": 55000
}

### Recuperar un budget por id
GET https://mockmentor.4.us-1.fl0.io/api/v1/budgets/7642b5bb-d52c-449f-aae7-b99e4c162464
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM


### Recuperamos todos los expenses de un usuario que hizo login
GET https://mockmentor.4.us-1.fl0.io/api/v1/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

### Creamos un expense
POST https://mockmentor.4.us-1.fl0.io/api/v1/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

{
  "name": "Pago del Cursos",
  "amount": 1300
}

### Recuperar un expense por su id
GET https://mockmentor.4.us-1.fl0.io/api/v1/expenses/cb2af9eb-cf9b-454d-a70a-ddff4727427e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

### Actualizamos un expense
PUT https://mockmentor.4.us-1.fl0.io/api/v1/expenses/cb2af9eb-cf9b-454d-a70a-ddff4727427e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM

{
  "name": "Pago de Cursos en Udemy",
  "amount": 1500
}

### Eliminamos un expense
DELETE https://mockmentor.4.us-1.fl0.io/api/v1/expenses/1bf5e246-cfc4-4099-a54f-7cae4b113a2d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYmJiZjJhNC1lMzMxLTQ2MDEtYmJkMS0zZWRkZmZmNDM5M2YiLCJmaXJzdG5hbWUiOiJBbG9uc28iLCJsYXN0bmFtZSI6IlZpbGxhesOzbiIsImlhdCI6MTcwOTM1MTcxOCwiZXhwIjoxNzA5MzU1MzE4fQ.hXVoCQdt-ON79bkqkw2CCh3Flesidi0U1hh9el8gqxM